name: fludemy
description: FLUdemy.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  effective_dart: ^1.3.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
